/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fcf9f2",
        "surface-dim": "#dcdad3",
        "surface-bright": "#fcf9f2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3ec",
        "surface-container": "#f1eee7",
        "surface-container-high": "#ebe8e1",
        "surface-container-highest": "#e5e2db",
        "on-surface": "#1c1c18",
        "on-surface-variant": "#474741",
        "inverse-surface": "#31312c",
        "inverse-on-surface": "#f3f0e9",
        "outline": "#777771",
        "outline-variant": "#c8c7bf",
        "surface-tint": "#5f5e5c",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1c1a",
        "on-primary-container": "#858481",
        "inverse-primary": "#c9c6c3",
        "secondary": "#904d00",
        "on-secondary": "#ffffff",
        "secondary-container": "#fd983b",
        "on-secondary-container": "#693600",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1d1c16",
        "on-tertiary-container": "#87837c",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e5e2de",
        "primary-fixed-dim": "#c9c6c3",
        "on-primary-fixed": "#1c1c1a",
        "on-primary-fixed-variant": "#474744",
        "secondary-fixed": "#ffdcc3",
        "secondary-fixed-dim": "#ffb77d",
        "on-secondary-fixed": "#2f1500",
        "on-secondary-fixed-variant": "#6e3900",
        "tertiary-fixed": "#e7e2d9",
        "tertiary-fixed-dim": "#cac6be",
        "on-tertiary-fixed": "#1d1c16",
        "on-tertiary-fixed-variant": "#494740",
        "background": "#fcf9f2",
        "on-background": "#1c1c18",
        "surface-variant": "#e5e2db"
      },
      borderRadius: {
        DEFAULT: "0px", // Angular 0px sharp corners per DESIGN.md
        "none": "0px",
        "sm": "0px",
        "md": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "gutter-desktop": "1.5rem",
        "space-2xl": "3rem",
        "space-2xs": "0.25rem",
        "space-4xl": "6rem",
        "space-lg": "1.5rem",
        "container-max": "1280px",
        "gutter-mobile": "1rem",
        "space-xl": "2rem",
        "space-md": "1rem",
        "space-sm": "0.75rem",
        "space-3xl": "4.5rem",
        "space-xs": "0.5rem"
      },
      fontFamily: {
        sans: ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"],
        "label-md": ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"],
        "headline-hero": ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"],
        "headline-md": ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"],
        "technical-code": ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"],
        "headline-lg": ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"],
        "label-sm": ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"],
        "body-lg": ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"],
        "headline-sm": ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"],
        "label-lg": ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
